BACKUP DATABASE ICT
TO DISK = '\\srv01\sql$\ITPROD.bak'
WITH INIT

RESTORE DATABASE ITTEST FROM disk = '\\srv01\sql$\ITPROD.bak'
WITH REPLACE, RECOVERY, 
MOVE 'ITPROD' TO 'C:\ClusterStorage\Volume13\MSSQL12.STD2014\MSSQL\DATA\ITPROD.mdf',
MOVE 'ITPROD_log' TO 'C:\ClusterStorage\Volume13\MSSQL12.STD2014\MSSQL\DATA\ITPROD_log.ldf'

-----------------------------

-- DECLARE Algemene vars
DECLARE @BACKUP_LOCATIE VARCHAR(MAX)
DECLARE @DBFILES_LOCATIE VARCHAR(MAX)
DECLARE @DBPROD VARCHAR(MAX)
DECLARE @DBTEST VARCHAR(MAX)

-- SET Algemene vars, HIER DRAAIT HET ALLEMAAL OM, ZORG DAT DIT GOED INGEVULD IS!!
SET @BACKUP_LOCATIE = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Backup\'
SET @DBFILES_LOCATIE = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\'
SET @DBPROD = 'ITPROD'
SET @DBTEST = 'ITTEST'

-- DECLARE Execute vars
DECLARE @EXECUTE_USE AS VARCHAR(MAX)
DECLARE @EXECUTE_BACKUP AS VARCHAR(MAX)
DECLARE @EXECUTE_RESTORE AS VARCHAR(MAX)
DECLARE @EXECUTE_RENAME_DATA AS VARCHAR(MAX)
DECLARE @EXECUTE_RENAME_LOG AS VARCHAR(MAX)

-- SET Execute vars
SET @EXECUTE_USE = 'USE '+@DBPROD+''
SET @EXECUTE_BACKUP = 'BACKUP DATABASE '+@DBPROD+' TO DISK = '''+@BACKUP_LOCATIE+''+@DBPROD+'.bak'' WITH INIT'
SET @EXECUTE_RESTORE = 'RESTORE DATABASE '+@DBTEST+' FROM DISK = '''+@BACKUP_LOCATIE+''+@DBPROD+'.bak'' WITH REPLACE, RECOVERY, MOVE '''+@DBPROD+''' TO '''+@DBFILES_LOCATIE+''+@DBTEST+'.mdf'', MOVE '''+@DBPROD+'_log'' TO '''+@DBFILES_LOCATIE+''+@DBTEST+'_log.ldf'''
SET @EXECUTE_RENAME_DATA = 'ALTER DATABASE '+@DBTEST+' MODIFY FILE (NAME=N'''+@DBPROD+''', NEWNAME=N'''+@DBTEST+''')'
SET @EXECUTE_RENAME_LOG = 'ALTER DATABASE '+@DBTEST+' MODIFY FILE (NAME=N'''+@DBPROD+'_log'', NEWNAME=N'''+@DBTEST+'_log'')'

-- EXECUTE alles
EXEC(@EXECUTE_USE); -- Gebruik database
EXEC(@EXECUTE_BACKUP); -- Backup productie database
EXEC(@EXECUTE_RESTORE); -- Restore test database met data van productie database
EXEC(@EXECUTE_RENAME_DATA); -- Rename logical data name
EXEC(@EXECUTE_RENAME_LOG); -- Rename logical log name
